# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(577, 443)
        Dialog.setSizeGripEnabled(False)
        self.pushButton2b = QtWidgets.QPushButton(Dialog)
        self.pushButton2b.setGeometry(QtCore.QRect(90, 120, 75, 23))
        self.pushButton2b.setObjectName("pushButton2b")
        self.pushButton2c = QtWidgets.QPushButton(Dialog)
        self.pushButton2c.setGeometry(QtCore.QRect(170, 120, 75, 23))
        self.pushButton2c.setObjectName("pushButton2c")
        self.label1b = QtWidgets.QLabel(Dialog)
        self.label1b.setGeometry(QtCore.QRect(30, 20, 121, 31))
        self.label1b.setStyleSheet("")
        self.label1b.setObjectName("label1b")
        self.photo = QtWidgets.QGraphicsView(Dialog)
        self.photo.setGeometry(QtCore.QRect(320, 10, 256, 431))
        self.photo.setObjectName("photo")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(10, 70, 301, 16))
        self.line.setStyleSheet("")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton1a = QtWidgets.QPushButton(Dialog)
        self.pushButton1a.setGeometry(QtCore.QRect(170, 50, 75, 23))
        self.pushButton1a.setObjectName("pushButton1a")
        self.label1a = QtWidgets.QLabel(Dialog)
        self.label1a.setGeometry(QtCore.QRect(10, 30, 47, 16))
        self.label1a.setStyleSheet("font: bold 18px;")
        self.label1a.setObjectName("label1a")
        self.label2a = QtWidgets.QLabel(Dialog)
        self.label2a.setGeometry(QtCore.QRect(10, 90, 47, 21))
        self.label2a.setStyleSheet("font: bold 18px;")
        self.label2a.setObjectName("label2a")
        self.label2b = QtWidgets.QLabel(Dialog)
        self.label2b.setGeometry(QtCore.QRect(30, 80, 161, 31))
        self.label2b.setStyleSheet("")
        self.label2b.setObjectName("label2b")
        self.pushButton2a = QtWidgets.QPushButton(Dialog)
        self.pushButton2a.setGeometry(QtCore.QRect(10, 120, 75, 23))
        self.pushButton2a.setObjectName("pushButton2a")
        self.label3a = QtWidgets.QLabel(Dialog)
        self.label3a.setGeometry(QtCore.QRect(10, 170, 47, 21))
        self.label3a.setStyleSheet("font: bold 18px;")
        self.label3a.setObjectName("label3a")
        self.label3b = QtWidgets.QLabel(Dialog)
        self.label3b.setGeometry(QtCore.QRect(30, 160, 251, 31))
        self.label3b.setStyleSheet("")
        self.label3b.setObjectName("label3b")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(10, 150, 301, 16))
        self.line_2.setStyleSheet("")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButton3a = QtWidgets.QPushButton(Dialog)
        self.pushButton3a.setGeometry(QtCore.QRect(170, 200, 75, 23))
        self.pushButton3a.setObjectName("pushButton3a")
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(10, 220, 301, 16))
        self.line_3.setStyleSheet("")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.pushButton4a = QtWidgets.QPushButton(Dialog)
        self.pushButton4a.setGeometry(QtCore.QRect(170, 270, 75, 23))
        self.pushButton4a.setObjectName("pushButton4a")
        self.label4a = QtWidgets.QLabel(Dialog)
        self.label4a.setGeometry(QtCore.QRect(10, 240, 47, 21))
        self.label4a.setStyleSheet("font: bold 18px;")
        self.label4a.setObjectName("label4a")
        self.label4b = QtWidgets.QLabel(Dialog)
        self.label4b.setGeometry(QtCore.QRect(30, 230, 161, 31))
        self.label4b.setStyleSheet("")
        self.label4b.setObjectName("label4b")
        self.line_4 = QtWidgets.QFrame(Dialog)
        self.line_4.setGeometry(QtCore.QRect(10, 290, 301, 16))
        self.line_4.setStyleSheet("")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label5a = QtWidgets.QLabel(Dialog)
        self.label5a.setGeometry(QtCore.QRect(10, 310, 47, 21))
        self.label5a.setStyleSheet("font: bold 18px;")
        self.label5a.setObjectName("label5a")
        self.line_5 = QtWidgets.QFrame(Dialog)
        self.line_5.setGeometry(QtCore.QRect(10, 340, 301, 16))
        self.line_5.setStyleSheet("")
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label5b = QtWidgets.QLabel(Dialog)
        self.label5b.setGeometry(QtCore.QRect(30, 300, 261, 41))
        self.label5b.setStyleSheet("")
        self.label5b.setObjectName("label5b")
        self.label6b = QtWidgets.QLabel(Dialog)
        self.label6b.setGeometry(QtCore.QRect(30, 350, 261, 41))
        self.label6b.setStyleSheet("")
        self.label6b.setObjectName("label6b")
        self.label6a = QtWidgets.QLabel(Dialog)
        self.label6a.setGeometry(QtCore.QRect(10, 360, 47, 21))
        self.label6a.setStyleSheet("font: bold 18px;")
        self.label6a.setObjectName("label6a")
        self.line_7 = QtWidgets.QFrame(Dialog)
        self.line_7.setGeometry(QtCore.QRect(10, 390, 301, 16))
        self.line_7.setStyleSheet("")
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(20, 410, 271, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton2b.setText(_translate("Dialog", "Y"))
        self.pushButton2c.setText(_translate("Dialog", "Z"))
        self.label1b.setText(_translate("Dialog", "Open .tif or .tiff file"))
        self.pushButton1a.setText(_translate("Dialog", "Open"))
        self.label1a.setText(_translate("Dialog", "1. "))
        self.label2a.setText(_translate("Dialog", "2."))
        self.label2b.setText(_translate("Dialog", "Choose orientation of stack"))
        self.pushButton2a.setText(_translate("Dialog", "X"))
        self.label3a.setText(_translate("Dialog", "3."))
        self.label3b.setText(_translate("Dialog", "Optional: Change the color map, open new color map file:"))
        self.pushButton3a.setText(_translate("Dialog", "Open"))
        self.pushButton4a.setText(_translate("Dialog", "Open"))
        self.label4a.setText(_translate("Dialog", "4."))
        self.label4b.setText(_translate("Dialog", "Generate the visualization"))
        self.label5a.setText(_translate("Dialog", "5."))
        self.label5b.setText(_translate("Dialog", "Go to localhost:8080 on your browser of choice\n"
" Chrome for Vive/Oculus and Edge for Windows Mixed Reality"))
        self.label6b.setText(_translate("Dialog", "Click the glasses icon on the lower right hand corner\n"
" to enter VR. "))
        self.label6a.setText(_translate("Dialog", "6."))

